### PR TITLE
import types

### PR DESCRIPTION
**Pull request by turadg**
## Description

Uses `@import` from upcoming TS 5.5, like https://github.com/Agoric/agoric-sdk/pull/9149

Also includes the changes needed in https://github.com/Agoric/agoric-sdk/commit/83db366359540c651fad9b7e3c192e7aa92634ea

### Security Considerations

Nightly build of TypeScript

### Scaling Considerations

no runtime changes

### Documentation Considerations

nothing to change

### Testing Considerations

CI

### Compatibility Considerations

Increases compatibility with agoric-sdk

### Upgrade Considerations

no runtime changes

- [ ] Includes `*BREAKING*:` in the commit message with migration instructions for any breaking change.
- [ ] Updates `NEWS.md` for user-facing changes.

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]
Ecstatic. I think I found the CI failure. Your changes were mechanical, but there was an existing type reference error that had gone unnoticed somehow. I changed one imported type from `Remotable` to `RemotableObject` and appended that commit to your branch (1faea7afc4ca2625aea1a0bde478eadeb992a987). Paging @erights if that’s consistent with the design.

**Comment by erights** [comment]
> Ecstatic. I think I found the CI failure. Your changes were mechanical, but there was an existing type reference error that had gone unnoticed somehow. I changed one imported type from `Remotable` to `RemotableObject` and appended that commit to your branch ([1faea7a](https://github.com/endojs/endo/commit/1faea7afc4ca2625aea1a0bde478eadeb992a987)). Paging @erights if that’s consistent with the design.

Yes. Glad to see this happening!

**Comment by erights** [comment]
windows-latest failed. But it is known to be flaky so I restarted it.

**Review by erights — APPROVED** [review]
Not a reviewer, but joining in out of enthusiasm ;)

**Pull request merged**
