### PR TITLE
DO NOT MERGE Safari defineProperties bug

### PR DESCRIPTION
**Pull request by erights**
The SES Demo console, after previously having worked on Safari Technology Preview, suddenly started failing with an infinite recursion. This instrumented variation of the PR in which this started failing catches when `Object.defineProperties` causes a setter to be called. The `Object.defineProperties` is attempting to convert `Array.prototype.toString` from a data property to an accessor property, after `Object.prototype.toString` has been similarly converted. Violating the semantics of `defineProperties`, it causes the setter of the `Object.prototype.toString` accessor property to be called. There follows some screenshots examining this state from within the debugger.

This is on Safari Technology Preview
Release 121 (Safari 14.2, WebKit 16612.1.4.3)

Reported as https://bugs.webkit.org/show_bug.cgi?id=222538

### CODE REVIEW

**Comment by erights** [comment]
Screen Shot 2021-03-01 at 12 36 06 AM
Screen Shot 2021-03-01 at 12 34 21 AM
Screen Shot 2021-03-01 at 12 32 12 AM
Screen Shot 2021-03-01 at 12 31 10 AM
Screen Shot 2021-03-01 at 12 30 41 AM
Screen Shot 2021-03-01 at 12 30 23 AM

**Comment by michaelfig** [comment]
Looks like this was already absorbed by the lenient stack traces PR, which I reviewed.  @erights LMK if this current 'DO NOT MERGE' PR still needs a review.

**Comment by erights** [comment]
I only added y'all as reviewers so you'd know about this issue. This PR itself exists *only* to demonstrate a bug to the WebKit developers. Sorry, I should have been clearer.

**Comment by erights** [comment]
It seems https://bugs.webkit.org/show_bug.cgi?id=222538 is now fixed! This PR's job is done. Closing.

**Comment by erights** [comment]
Reopening to track https://bugs.webkit.org/show_bug.cgi?id=222538#c17

**Comment by erights** [comment]
Doh! This is a PR not an issue. Closing.

**Pull request closed without merging**
