### PR TITLE
fix: add "name" to moderate overrideTaming of all errors

### PR DESCRIPTION
**Pull request by erights**

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]

**Comment by kriskowal** [comment]
We could test this, either directly or by inducing Node.js to attempt to create an error, but if you're satisfied that the existing feature tests cover the behavior, I have no argument.

**Comment by kriskowal** [comment]
We could also leave a note in NEWS.md.

**Comment by erights** [comment]
Sorry, I missed the NEWS.md comment. I'll do that now.

**Comment by erights** [comment]
Actually, while do that, could you put an issue somewhere, anywhere I can point at, explaining the anomalous Node behavior, with that code snippet, so I can cite that bug in my NEWS.md note? Thanks.

**Comment by kriskowal** [comment]
https://github.com/endojs/endo/issues/868

**Pull request merged**
