### PR TITLE
fix(ses)!: remove __allowUnsafeMonkeyPatching__

### PR DESCRIPTION
**Pull request by erights**
Well after https://github.com/Agoric/agoric-sdk/pull/5922 removes uses of this unsafe kludgy option, this PR removes the option itself. Good riddance!

### CODE REVIEW

**Comment by kriskowal** [comment]
@samsiegart How confident are you that we’ve solved this problem once and for all, that our UIs can run under lockdown going forward?

**Review by samsiegart — APPROVED** [review]

**Comment by erights** [comment]
@kriskowal this is technically a breaking change, although we've already updated agoric-sdk, which is likely the only one who cares. Do we need a deprecation dance, or can I go ahead and merge this?

**Comment by kriskowal** [comment]
The breaking-change version bump induced by a conventional commit message
will suffice. We do not need to do a two phase deprecation and removal
migration.

**Review by kriskowal — APPROVED** [review]
Please change the commit message prefix to fix(ses)!: and use the rebase merge.

**Comment by kriskowal** [comment]
Oh, and update NEWS.md

**Pull request merged**
