### PR TITLE
Add tests for backslash behavior

### PR DESCRIPTION
**Pull request by erights**
Test suggested by @kriskowal

### CODE REVIEW

**Comment by erights** [comment]
Added security label only because, if there was any platform on which this test fails, that would be security significant.

**Review by kriskowal — APPROVED** [review]

**Comment by kriskowal** [comment]
Testing for eval or import specifically might be more meaningful, but I assume this translates.

**Comment by kriskowal** [comment]
Poke. This has a stamp and needs a rebase to land.

**Comment by erights** [comment]
Whoa, blast from the past. Thanks for the poke.

**Pull request merged**
