### PR TITLE
WIP Slow but constant time emulation of WeakMap and WeakSet

### PR DESCRIPTION
**Pull request by erights**
An emergency measure for platforms where WeakMap and WeakSet take more than constant time. Just in case. 

NOT TO BE MERGED UNLESS IT ACTUALLY HELPS.

### CODE REVIEW

**Comment by erights** [comment]
This one doesn't work because our tooling does not understand class private instance fields. See https://github.com/endojs/endo/pull/704 instead.

**Comment by FUDCo** [comment]
This looks fine, albeit weird, but I think I'm missing some context.  What is the motivation for this?

**Comment by erights** [comment]
> This looks fine, albeit weird, but I think I'm missing some context. What is the motivation for this?

We're still trying to figure it out, but currently we're worried that XS WeakMap and WeakSet operations are not constant time, independent of the size of the maps/sets. If so, this may be a useful emergency measure. But I sure hope we don't need it!

**Comment by FUDCo** [comment]
I'd be concerned that WeakMaps and private instance fields would use the same underlying machinery (certainly how I'd implement them) and thus this workaround might not.

**Comment by erights** [comment]
> I'd be concerned that WeakMaps and private instance fields would use the same underlying machinery (certainly how I'd implement them) and thus this workaround might not.

Yes. @dtribble raised this worry too. It might. I've already asked @phoddie and @patrick-soquet . If so, this PR is completely pointless.

**Comment by erights** [comment]
@dckc tried it (thanks!) and it uniformly makes things worse. Closing.

**Pull request closed without merging**
