### PR TITLE
feat(stream)!: Protect streams against reentrance

### PR DESCRIPTION
**Pull request by kriskowal**
This is a proposed change that would by default protect stream methods from reentrance by defering method invocations to subsequent turns.  However, it does not work because eventual-send hardens arguments, and for streams, sending a typed array must be a valid interaction.

I propose that harden needs to treat typed arrays as a special case of collections like Map and Set, which can be hardened. The typed arrays are equally mutable, in that their content is mutable. Hardening a typed array could instead prevent extensions and make its non-content properties non-configurable.

### CODE REVIEW

**Comment by erights** [comment]
> make its non-content properties non-configurable

did you mean

make its non-content properties non-configurable non-writable

?

**Comment by kriskowal** [comment]
> > make its non-content properties non-configurable
> 
> did you mean
> 
> make its non-content properties non-configurable non-writable
> 
> ?

yes

**Review by erights — COMMENTED** [review]
If we successfully do the `harden` change you suggest, then this will LGTM.

And I am hopeful about that `harden` change.

**Comment by kriskowal** [comment]
Blocked by #1029

**Comment by kriskowal** [comment]
Hopes in the `harden` change have proven fruitful without modification here so I’ve opened this up for review.

**Review by erights — APPROVED** [review]
LGTM!

**Pull request merged**
