### PR TITLE
test(cli): Fix failing cli tests

### PR DESCRIPTION
**Pull request by sirtimid**
Closes: https://github.com/endojs/endo/issues/2409
Refs: https://github.com/endojs/endo/pull/2384

## Description

This PR updates the readme to properly document the `list` cli command and fixes the failing tests

### Security Considerations

none
### Scaling Considerations

none
### Documentation Considerations

none
### Testing Considerations

none
### Compatibility Considerations

none
### Upgrade Considerations

none

### CODE REVIEW

**Review by rekmarks — APPROVED** [review]
LGTM!

**Review by rekmarks — CHANGES_REQUESTED** [review]
Actually, the incremental commits of this PR need to to be converted into conventional commits.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Review by kriskowal — APPROVED** [review]

**Comment by kriskowal** [comment]
@sirtimid Please rebase on `origin/master`, force push, then use the “create a merge commit” button. This will keep the history clean: parallel linked lists with occasional merge knots.

**Comment by kriskowal** [comment]
@sirtimid Since you only have one significant commit, “squash merge” is also fine. The default commit message for the merge commit is your description above, which is also fine as writ.

**Pull request merged**
