### PR TITLE
toward SES testing on XS (WIP)

### LINKED ISSUE #508: integrate XS into SES-shim ci build / test
briefly...

https://github.com/Agoric/agoric-sdk/pull/1649 https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/Makefile and see the submodule in https://github.com/Agoric/agoric-sdk/tree/master/packages/xs-vat-worker 

@kriskowal had a less than enthusiastic reply to the submodule approach

there's also the issue of doing this on macos, possibly using docker...

cc @warner @erights

### LINKED ISSUE #535: SES shim testing on XS: "tiny ava"
@kriskowal , @erights , my previous work is https://github.com/agoric-labs/tape-xs last revised Jan 27 0fbe38c

Fortunately, I was on my game back then and made a nice README, complete with limitations and such. I think I even got @michaelfig to review it, so he may remember a little bit about it.

(for my reference: see also https://github.com/Agoric/agoric-sdk/issues/370 , https://github.com/Agoric/agoric-sdk/issues/49 )

### PR DESCRIPTION
**Pull request by dckc**
goal:
fixes #508
fixes #535

TODO:
 - [ ] change lint config so `import 'ses/lockdown';` is allowed
 - [ ] make sure xsnap builds before test
 - [ ] add `test:xs` to ci job
 - [ ] polish git history
   - [ ] prune the `feat(ava-xs): skip module-shim` stuff
   - [ ] squash moddable updates
   - [ ] squash xsnap lint config

After this PR at some point:
 - [ ] finish migrating `xsnap` and `ava-xs` from `agoric-sdk` (IOU an issue)

### CODE REVIEW

**Comment by erights** [comment]
What is the status of this PR?

**Comment by dckc** [comment]
> What is the status of this PR?

The only think I can think of that's not in the description etc. is that it's blocked on moving xsnap to endo (#681), which is not high on my list nor @kriskowal 's.

I suppose if #508 and #535 still belong on [the Endo 1 milestone](https://github.com/endojs/endo/milestone/2) then #681 should be there too. Thoughts, @kriskowal ?

**Comment by erights** [comment]
What is the status of this PR? Is it still relevant?

**Comment by dckc** [comment]
It's tangentially relevant in that migrating xsnap to endo (#681) is still on our todo list.

But I think the odds that we'll actually use these bits to accomplish that are sufficiently low that I'm closing this.

**Pull request closed without merging**
