### PR TITLE
Rename 'fit' to 'mustMatch'

### PR DESCRIPTION
**Pull request by FUDCo**
Per https://github.com/Agoric/agoric-sdk/issues/6844

### CODE REVIEW

**Comment by turadg** [comment]
What's the motivation?

If we're going to make it so long, why not "assertMatch"?

**Comment by kriskowal** [comment]
I’ve seen and like the `mustX` convention for functions whose behavior is to throw if `X` returns false. I’ve seen it used like `mustFind` or `mustQuerySelector`. I first saw the pattern used in Go, then in JavaScript among friends who also wrote Go. I don’t object to `assertX`.

**Comment by FUDCo** [comment]
I think this is one problem with cross-repo changes.  The relevant issue is https://github.com/Agoric/agoric-sdk/issues/6844

**Comment by turadg** [comment]
That issue provides the context I needed. I've put it in the PR description.

**Review by turadg — APPROVED** [review]
Thanks @kriskowal for the explanation of the "must" naming pattern.

**Pull request merged**
