### PR TITLE
fix(ses): better safari debugging

### PR DESCRIPTION
**Pull request by erights**
Fixes https://github.com/endojs/endo/issues/1490

See that issue for explanation.

@argp1 I cannot add you as an official reviewer, but please review anyway. Thanks.

### CODE REVIEW

**Comment by erights** [comment]
Given the nature of the bug this fixes, I have no idea how to write an automated test for it.

**Comment by mhofman** [comment]
@erights looks like you need to update the `all other handlers throw errors` test, which is now failing.

**Comment by erights** [comment]
> @erights looks like you need to update the `all other handlers throw errors` test, which is now failing.

Done

**Review by mhofman — APPROVED** [review]
Looks good. I don't think we need more tests than this.

**Pull request merged**
