### PR TITLE
doc(ses): delete obsolete sphinx support

### LINKED ISSUE #1735: ses/docs has stale stuff from when we used Read the Docs and Sphinx
https://github.com/endojs/endo/blob/9956f044a3a0ccd5c9241781ed5c470e3f45542d/packages/ses/docs/README.md?plain=1#L3

says

> The [SES documentation](https://ses-secure-ecmascript.readthedocs.io/en/latest/) is hosted by Read the Docs, and is built using
[Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html).

Following that first link takes us to 

image

which still has the title, but no longer any content. Clicking on the "Edit on GitHub" link there takes us to

image

AFAIK, we no longer intend to maintain this site, in which case we should stop linking to it and somehow delete the page itself. We also seem to have several files whose purpose seems to be to maintain that site. If we no longer intend to maintain that site, we should also delete the following files:

https://github.com/endojs/endo/blob/master/packages/ses/docs/make.bat
https://github.com/endojs/endo/blob/master/packages/ses/docs/Makefile
https://github.com/endojs/endo/blob/master/packages/ses/docs/source/conf.py
https://github.com/endojs/endo/blob/master/packages/ses/docs/source/index.rst
https://github.com/endojs/endo/blob/master/packages/ses/docs/source/draft-standalone-spec.rst (Is this generated from https://github.com/endojs/endo/blob/master/packages/ses/docs/source/draft-standalone-spec.md , or vice versa?)

We should also move https://github.com/endojs/endo/blob/master/packages/ses/docs/source/draft-standalone-spec.md to somewhere more appropriate.

### PR DESCRIPTION
**Pull request by erights**
Fixes #1735 

Or rather, fixes the part that can be fixed within the endo repo. The remaining issue is to actually delete the bogus page at https://ses-secure-ecmascript.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by dckc** [comment]
I tried to see if there are many links to that material, but instead, I learned that [Google removed the link operator in 2017](https://searchengineland.com/google-officially-killed-off-link-command-267454).

**Comment by erights** [comment]
FWIW https://www.google.com/search?q=https%3A%2F%2Fses-secure-ecmascript.readthedocs.io%2F&oq=https%3A%2F%2Fses-secure-ecmascript.readthedocs.io%2F&aqs=chrome..69i58j69i57j69i60l2.8222j0j4&sourceid=chrome&ie=UTF-8 is a Google search on the url.

Opinions? Recommendations?

**Comment by dckc** [comment]
not enough links to bother with, IMO

**Comment by erights** [comment]
> not enough links to bother with, IMO

Agreed. I still need an approval though ;)

**Review by dckc — APPROVED** [review]
oh. right. that :)

**Pull request merged**
