### PR TITLE
chore: Migrate marshal and nat from Agoric SDK

### PR DESCRIPTION
**Pull request by kriskowal**
Refs #506

### CODE REVIEW

**Comment by kriskowal** [comment]
Looks like `marshal` can’t import `nat` on Node.js 12. cc @michaelfig 

Obvious option is to drop Node.js 12 from CI. Less obvious is addressing the issue with Nat, which is certainly because of named exports support in Node.js itself.

**Comment by michaelfig** [comment]
> Looks like `marshal` can’t import `nat` on Node.js 12. cc @michaelfig

`@agoric/nat` is a CommonJS module with multiple `exports.something = foo;` lines.  What tools do you have at your disposal for CommonJS interop?

**Comment by kriskowal** [comment]
> > Looks like `marshal` can’t import `nat` on Node.js 12. cc @michaelfig
> 
> `@agoric/nat` is a CommonJS module with multiple `exports.something = foo;` lines. What tools do you have at your disposal for CommonJS interop?

Source is ESM and Nat is using Rollup. I think integration in Endo is the right way to go, giving us an opportunity to kick off Rollup and RESM.

**Review by michaelfig — APPROVED** [review]
LGTM!  Nice to adopt the `@endo/nat` straggler.

**Pull request merged**
