### PR TITLE
refactor(daemon,cli): Rename capitalized names and arguments

### PR DESCRIPTION
**Pull request by rekmarks**
- Uncapitalizes all "special names" in the daemon, since we have determined we no longer need this.
- Renames the `--UNSAFE` CLI flag to `--UNCONFINED`, which is more specific. We maintain capitalization here to draw attention to it.

### CODE REVIEW

**Review by kriskowal — CHANGES_REQUESTED** [review]
I’ve miscommunicated again!

We do actually need special names to be capitalized to distinguish them from pet names in the pet store. For example, the name `HOST` is not deletable whereas `host` can be assigned.

There is no need for the third term in `INFO.host.worker` to be capitalized under a pet inspector.

**Comment by kriskowal** [comment]
(Renaming `--UNSAFE` to `--UNCONFINED` is good and @dckc will thank you!)

**Comment by rekmarks** [comment]
Alas dear PR, I barely knew ye...

**Comment by kriskowal** [comment]
I should also clarify that the design requirement is that special names and pet names need to be distinguishable. This is just the convention of the day and can be changed. We want pet names to have a much more broad range. The distinguisher could be something else. A dot prefix (`.self`, `guest..self`)?

**Pull request closed without merging**
