### PR TITLE
test: Replace misleading test

### PR DESCRIPTION
**Pull request by gibson042**
arguments objects don't have a special prototype

Ref 5c41bdc0628d69a83a1c9378e986573444f2bb1d

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]

**Review by naugtur — APPROVED** [review]

**Comment by kriskowal** [comment]
Perhaps it would be instructive to capture an assertion that the arguments
prototype is in fact null. It is frozen by virtue of Object.isFrozen(null)
=== true.

**Comment by gibson042** [comment]
The prototype isn't null, it's `Object.prototype`.

**Comment by kriskowal** [comment]
Pardon, as it were!

**Comment by naugtur** [comment]
^ I'd say that adds grounds to my claim that we need to demonstrate arguments.__proto__ is frozen regardless of what you think it is.

**Comment by naugtur** [comment]
The only thing that's special is the number of people knowing JS very well that were unsure what's the prototype of arguments.
I have this occasional itch to document surprising stuff with tests if not too time consuming. But I'm not orthodox about it ;)

**Pull request merged**
