### PR TITLE
feat: Restore recast-based whitespace preservation

### PR DESCRIPTION
**Pull request by kriskowal**
- Revert "Revert "fix(static-module-record): minimise source changes with `recast`""
- Revert "Revert "build(deps): add a patched version of `recast`""
- fully patch agoric-labs/ast-types#Agoric-built

### CODE REVIEW

**Comment by michaelfig** [comment]
@kriskowal care to have a review of this?  I moved the ast-types patch to https://github.com/agoric-labs/ast-types/tree/Agoric-built

**Comment by kriskowal** [comment]
Looks good to me, but evidently, as an author of the PR, I cannot review. My only nit is that I think the at-types patch commit can be rebased out.

**Review by michaelfig — APPROVED** [review]
Self-approval based on @kriskowal's and my reviews.

**Comment by kriskowal** [comment]
I think this just needs a rebase-and-land @michaelfig. The #506 migration is complete now, so landing is an adequate synchronization risk now.

**Pull request merged**
